#!/bin/bash

apt-get update

# Install all unique required packages
apt-get install -y \
    automake \
    bwidget \
    cargo \
    chromium \
    cmake \
    coinor-libclp-dev \
    coinor-libsymphony-dev \
    coinor-symphony \
    dcraw \
    default-jdk \
    gdal-bin \
    git \
    gsfonts \
    haveged \
    imagej \
    jags \
    libapparmor-dev \
    libarchive-dev \
    libavfilter-dev \
    libboost-all-dev \
    libbz2-dev \
    libcairo2-dev \
    libcurl4-openssl-dev \
    libfftw3-dev \
    libflint-dev \
    libfluidsynth-dev \
    libfontconfig1-dev \
    libfreetype6-dev \
    libfribidi-dev \
    libgdal-dev \
    libgeos-dev \
    libgit2-dev \
    libgl1-mesa-dev \
    libglib2.0-dev \
    libglpk-dev \
    libglu1-mesa-dev \
    libgmp3-dev \
    libgpgme11-dev \
    libgrpc++-dev \
    libgsl0-dev \
    libharfbuzz-dev \
    libhdf5-dev \
    libhiredis-dev \
    libicu-dev \
    libimage-exiftool-perl \
    libjpeg-dev \
    libjq-dev \
    libleptonica-dev \
    liblzma-dev \
    libmagic-dev \
    libmagick++-dev \
    libmecab-dev \
    libmpfr-dev \
    libmysqlclient-dev \
    libnetcdf-dev \
    libnode-dev \
    libopencv-dev \
    libopenmpi-dev \
    libpng-dev \
    libpoppler-cpp-dev \
    libpoppler-glib-dev \
    libpq-dev \
    libproj-dev \
    libprotobuf-dev \
    libprotoc-dev \
    libqgis-dev \
    libquantlib0-dev \
    librdf0-dev \
    librsvg2-dev \
    libsasl2-dev \
    libsecret-1-dev \
    libsndfile1-dev \
    libsodium-dev \
    libsqlite3-dev \
    libssh-dev \
    libssh2-1-dev \
    libssl-dev \
    libtesseract-dev \
    libtiff-dev \
    libudunits2-dev \
    libwebp-dev \
    libx11-dev \
    libxml2-dev \
    libxslt-dev \
    libzmq3-dev \
    libzstd-dev \
    make \
    nvidia-cuda-dev \
    ocl-icd-opencl-dev \
    pandoc \
    pandoc-citeproc \
    pari-gp \
    patch \
    perl \
    pkg-config \
    protobuf-compiler \
    protobuf-compiler-grpc \
    python3 \
    rustc \
    saga \
    software-properties-common \
    tcl \
    tesseract-ocr-eng \
    texlive \
    tk \
    tk-dev \
    tk-table \
    unixodbc-dev \
    xz-utils \
    zlib1g-dev

# Reconfigure Java for R
R CMD javareconf

